# Generated by Django 5.2.7 on 2025-11-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_type_mcq',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question_type_msq',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question_type_numerical',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
