# Generated by Django 5.2.7 on 2025-10-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
