# Generated by Django 5.2.7 on 2025-11-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='answers_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='time_spent_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='total_marks',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('msq', 'MSQ'), ('numerical', 'Numerical')], max_length=20)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.FloatField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='student.examattempt')),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
    ]
